[package]
name = "collission_sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.14"
image = "0.24.5"
thiserror = "1.0"

[dependencies.glfw]
git = "https://github.com/bjz/glfw-rs.git"
